Test coff arch refactor
Vector35/arch-armv7 pull request #58
Opened 2021-10-28 01:34 UTC by galenbwill

COFF loading support complete

2021-10-28 01:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Vector35/arch-armv7?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Vector35/arch-armv7?pullRequest=58) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: galenbwill<br/>:x: bpotchik<br/>:x: lwerdna<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Vector35/arch-armv7?pullRequest=58) it.</sub>

2021-10-29 14:59 UTC, plafosse requested changes
that one line I made a comment on probably needs to change, other then that it looks good

2021-10-29 14:59 UTC, plafosse commented on arch_armv7.cpp
> +			if (true || arch->GetName() == "thumb2")
? what's this condition for?

2021-10-29 14:59 UTC, plafosse commented on arch_armv7.cpp
> +				// This could be done more efficiently with shifts, ands, and ors, but that's the compiler's job
🤌

2021-11-02 21:39 UTC, galenbwill commented on arch_armv7.cpp
> +			if (true || arch->GetName() == "thumb2")
an unnecessary check that should have been removed

2021-11-02 21:40 UTC, galenbwill commented
this PR is out of date

2021-11-02 21:40 UTC, closed without merging